version: '3.8'
services:
    mariadb:
        image: mariadb
        env_file: ./.env
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql:
    mysql_config: